### ISSUE TITLE
Adding a curated list of psr7 middlewares

### ISSUE THREAD

**Issue by lalop** [slimphp/Slim-Website#100]
I think we could add a curated list of middleware in the doc to help user to build their stack.

**Comment by gurpreetatwal** [comment]
+1 This would be incredibly useful

**Comment by DavidePastore** [comment]
Some middlewares are available in the [wiki](https://github.com/slimphp/Slim/wiki/Middleware-for-Slim-Framework-v3.x), but we could improve it and move on the website.

**Comment by lalop** [comment]
or at least add a link to this page

**Comment by lalop** [comment]
Hello,

I finally start my own list https://github.com/lalop/awesome-psr7 
It's a work in progress as you can see but any information on known middleware is welcome.

**Comment by svpernova09** [comment]
Is there still work to be done here or did #253 accomplish the goals?

**Comment by akrabat** [comment]
I'd call this one done.

There's now an obvious place to put it if someone wants to add additional items.
