### ISSUE TITLE
How to install a local copy of Slim documentation 

### ISSUE THREAD

**Issue by ismnoiet** [slimphp/Slim-Website#106]
I have the documentation for Slim 3 and it is working like a charm,
but for some reasons i'm using Slim 2,
the online documentation is pretty good and can be found at : 

http://docs.slimframework.com/

What i want is the previous documentation source code(version 2) so i can build it and use it locally.

**Comment by ppetermann** [comment]
you mean as in https://github.com/slimphp/Slim-Documentation-2.x ?

**Comment by ismnoiet** [comment]
Thank you very much this is exactly what i'm looking for.
