### ISSUE TITLE
Better documentation for App Settings

### ISSUE THREAD

**Issue by JoshWillik** [slimphp/Slim-Website#126]
Hey guys.

I was halfway through forking the website to add documentation for `\Slim\App` construction when I found that the options I was documenting were already laid out in [the dependency container docs](http://www.slimframework.com/docs/concepts/di.html). This wouldn't have been my first guess as someone new to Slim 3. (Last experience was Slim 2).

I not sure exactly how, but is it possible to give this information a bit of a higher profile on the website?

This isn't a firm stance, I just thought that my initial, pseudo-beginner reaction might prove useful.

Thanks for the cool library :+1:

**Comment by silentworks** [comment]
Thanks for your feedback, where do you think this would be more suited to be in the documentation?

**Comment by JoshWillik** [comment]
When I was creating my fork, I had a section called "The Application" above
"The Request". It had "Overview" and "Configuration" subsetting.

That's where I expected to find it, anyway.

**Comment by akrabat** [comment]
Sounds good to me. Do you want to submit a PR for that?

**Comment by JoshWillik** [comment]
It's a bit bare bones right now, can you guys think of anything else that should be added?

**Comment by JoshWillik** [comment]
Thanks @akrabat! You expressed things way better than I could.

I appreciate the quick response on this!
