### ISSUE TITLE
Search facility for documentation

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Website#139]
The ability to search on the site would be nice!

Possible option: http://www.tipue.com/search/

**Comment by geekish** [comment]
Saw this on couscousphp/couscous#63; it's a different approach, but I thought I'd suggest it. :)
https://community.algolia.com/docsearch/

**Comment by geggleto** [comment]
What about google search? I thought they had some kinda tool for searching and indexing the pages?

**Comment by codeguy** [comment]
I was going to https://www.algolia.com/. They have an open source plan:

https://www.algolia.com/doc/faq/accounts-billing/i-develop-an-open-source-or-not-for-profit-project

I've only heard good things about them.

**Comment by codeguy** [comment]
Ha.  Looks like @geekish beat me to it :)

**Comment by codeguy** [comment]
Working on this today.

**Comment by dopesong** [comment]
This can be closed
