### ISSUE TITLE
Add a license to the documentation

### ISSUE THREAD

**Issue by Ettapp** [slimphp/Slim-Website#145]
(Please apologise my english)

I wanted to suggest to the team of http://devdocs.io/ to take a look at you're doc to use it in their tool, but they need to be sure that they don't break the documentation license, and as I don't find it anywhere I suppose that there is any actually...

(first issue ever, and not realy comfortable with english, don't hesitate to tell me if I did somethink wrong or if something could be better :-) )

**Comment by akrabat** [comment]
One for @codeguy.

**Comment by sillevl** [comment]
Any news on the license?  I teach Slim in my course of web scripting and want to bundle the documentation on paper for my students.

**Comment by codeguy** [comment]
License added 👍 

https://www.slimframework.com/docs/

**Comment by akrabat** [comment]
Thanks @codeguy  :)

**Comment by Ettapp** [comment]
Thanks ! :-D

**Comment by sillevl** [comment]
Thanks !
