### ISSUE TITLE
Next, previous button in user guide

### ISSUE THREAD

**Issue by SusanthCom** [slimphp/Slim-Website#166]
Hi,

If provided, Next, Previous buttons in user guide section at bottom of every page, that will provide smooth navigation, especially for those who are new to slim. 

As of now, at the end of a page, one has to scroll up. Also there is no indicator for current page. Making page title bold will solve this. 

Thanks

**Comment by akrabat** [comment]
We would love a contribution that implements this.

**Comment by silentworks** [comment]
We currently have a PR that will be merged soon that indicate the page you are currently viewing. #156
