### ISSUE TITLE
The Structure Described in First Application Guide Differs from Slim-Skeleton?

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim-Website#171]
The directory structure of the app described at [First Application](http://www.slimframework.com/docs/tutorial/first-app.html#getting-set-up) in the documentation differs from one in [Slim-skeleton](https://github.com/slimphp/Slim-Skeleton) repo, so what structure is the best?

**Comment by akrabat** [comment]
Whatever floats your boat. Slim doesn't enforce a structure.

I quite like the structure in https://github.com/akrabat/slim3-skeleton

**Comment by ghost** [comment]
Yes, I know that Slim doesn't depend on or enforces any particular structure, but while I was studying Slim's documentation I thought that the guidance must match the skeleton and/or the skeleton must match the documentation.

I really liked the link you provided.

**Comment by geggleto** [comment]
Going to close this one :)
