### ISSUE TITLE
CORS Example does not work

### ISSUE THREAD

**Issue by moritz-h** [slimphp/Slim-Website#184]
There are some Problems with the second CORS example (after the simple solution) here:
http://www.slimframework.com/docs/cookbook/enable-cors.html

The line `$pattern = $request->getAttribute("route")->getPattern();` throws an error if you call an invalid route. If the route does not exist `$request->getAttribute("route")` is `null` and then `null->getPattern()` throws an Error.
Should be at least something like:
`$pattern = $request->getAttribute("route") ? $request->getAttribute("route")->getPattern() : null;`

Also the second example does not answer to OPTIONS Requests.
You can add the OPTIONS wildcard from the simple example above, but then the pattern is the wildcard and the simple string compare to all routes from the router does never match. So the header would be just set to `access-control-allow-methods: OPTIONS`, even if GET or POST route exists.

And last the line
`return $response->withHeader("Access-Control-Allow-Methods", implode(",", $methods);`
is missing a closing bracket at the end.

**Comment by geggleto** [comment]
> $request->getAttribute("route")

Will always return a route if and only if the `"determineRouteBeforeAppMiddleware" => true` config is set.

Please raise the issue on 2nd example on the Slim-Website Repo

**Comment by DracotMolver** [comment]
Even setting "determineRouteBeforeAppMiddleware" => true config, you will get an error

>  Call to a member function getPattern() on a non-object

can this be prevent using try and catch? (I just thought that right now lol)
