### ISSUE TITLE
Webpage documentation issue

### ISSUE THREAD

**Issue by RTCeables** [slimphp/Slim-Website#185]
Sorry I'm a stickler for documentation. In your website you note

"We recommend you install the Slim Framework with the Composer dependency manager." Yes super cool but then you do not state how. In gitub though you do... So suggest you add in this important line of text into your homepage to prevent confusion, as I was rather baffled at first by the next sentence on your homepage.

SO INSERT INTO HOMEPAGE:

$ composer require slim/slim "^3.0"
This will install Slim and all required dependencies. Slim requires PHP 5.5.0 or newer.

**Comment by akrabat** [comment]
Where is this? On the home page I see:

https://i.19ft.com/f62e7ad8.png

We want to encourage use of the skeleton, so this is what's our home page.

However, if you don't want to use the skeleton app, then the [Installation page](http://www.slimframework.com/docs/start/installation.html) of the docs starts with:

https://i.19ft.com/a961f2c4.png

**Comment by geggleto** [comment]
Perhaps a little clarification is required on the home page?...

We recommend you grab the skeleton if you are new to slim ...
composer create-project ...

Or if you just want he bare bones
composer require slim/slim "^3.0"

Thoughts @akrabat ?

**Comment by RTCeables** [comment]
Ok that is fair comment. Maybe then it is a case of stating the obvious after this sentence "Replace [my-app-name] with the desired directory name for your new application." with

This will install slim and all the dependencies etc.

**Comment by akrabat** [comment]
@geggleto I don't want the home page to mention bare bones - it creates additional support queries.

**Comment by akrabat** [comment]
> Ok that is fair comment. Maybe then it is a case of stating the obvious after this sentence "Replace [my-app-name] with the desired directory name for your new application." with
> 
> This will install slim and all the dependencies etc.

That's a good idea. Fancy submitting a PR?

**Comment by DracotMolver** [comment]
Why you don't put below of 

> We recommend you install the Slim Framework with the Composer dependency manager.

The image from https://i.19ft.com/a961f2c4.png

So the info will be mmmm, persistent no matter if you are in the home or in the installation page :)

**Comment by geggleto** [comment]
Going to close this one; Slim needs composer for v3+
