### ISSUE TITLE
Translation to Japanese

### ISSUE THREAD

**Issue by satt03** [slimphp/Slim-Website#203]
Hi. We, my team at a company in Japan, would like to translate your Slim-Website to Japanese as volunteers, so that more Japanese engineers are able to choose Slim framework easily.
If possible, would you create a function which viewers can change language easily such as [PHP Manual](http://php.net/manual/en/).

**Comment by akrabat** [comment]
Okay, I'm ready to take this on now.

We'll need a PR that adds Japanese along with a way to select language.

**Comment by satt03** [comment]
Thanks. We are going to start its translation tomorrow.
Regarding to a way to select language, do you have any ideas or preferable style on your website?

**Comment by akrabat** [comment]
Not really. I would assume that we may get more languages, so it should be extensible.

It also needs to be easy to switch back to English if you don't speak whatever language its currently in.

**Comment by satt03** [comment]
I agree with its idea. Let me have some time for PR.

**Comment by ousid** [comment]
hey, @akrabat  any news about the translation? I would translate the website to the Arabic language too if you like.

**Comment by akrabat** [comment]
> hey, @akrabat any news about the translation? I would translate the website to the Arabic language too if you like.

I've not heard anything and I guess @l0gicgate hasn't either.

**Comment by l0gicgate** [comment]
This is a pretty big undertaking to include languages for the docs. I feel it's almost easier to just use Chrome's translation feature to achieve this. I don't have the time to do this unfortunately.

**Comment by ddrv** [comment]
@l0gicgate, @akrabat 
We have translations into Russian for [version 3](https://slimframework.ru/v3) and some drafts for [version 4](https://slimframework.ru/v4). [There is a repository](https://github.com/slimframework-ru/slim.ru) with translations.
I think multilingual communities have something similar (you can ask in slack)

**Comment by odan** [comment]
Managing multiple languages is not possible in the long run.
Therefore, I propose we close this issue (and similar issues), and concentrate on the english documentation. 

Any objections? @akrabat @l0gicgate
