### ISSUE TITLE
Upgrade guide could be improved

### ISSUE THREAD

**Issue by eppeters** [slimphp/Slim-Website#206]
Referring to the upgrade guide here: https://www.slimframework.com/docs/start/upgrade.html

#24 had some good suggestions, and all got implemented except this item:

- upgrade guide for slim3 does not include information about Slim\Slim changing to Slim\App

Additionally, I noticed the upgrade guide mentions that the route function signature has changed, and specifically shows that the `$res` and `$req` parameters have been added to the callback signature. The guide does not, however, mention the important point that the request and response objects are no longer accessible via the `$app` (`\Slim\App`) object, which was a (the?) way to access them in 2.x

Here's a sample of some working 2.x code that does not work in 3.x:

```
    $app->post('/login', function () use ($app, $json_result) { // breaks due to documented signature change
        $username = $app->request->post('username'); // breaks, but not documented
        $password = $app->request->post('password'); // breaks, but not documented

Error caused by line 2: Error\nMessage: Call to a member function post() on null
```

It wasn't terribly difficult to figure this out, but after reading the upgrade guide, I decided to jump in and got a rude awakening :)

I'd be happy to make these changes, but I've never contributed here before.

Thanks!

**Comment by akrabat** [comment]
Hey @eppeters! We'd love you to contribute the changes. The basic process is:

1. Fork this rep
2. Clone your fork to your computer
3. Create a new branch for this change
4. Make the change
5. Test it locally 
6. Push branch to your fork
7. Create pull request using GitHub

More detail can be found at https://akrabat.com/the-beginners-guide-to-contributing-to-a-github-project/

**Comment by eppeters** [comment]
Great @akrabat. I'll get to it.
