### ISSUE TITLE
Add Slim APIs reference

### ISSUE THREAD

**Issue by ghost** [slimphp/Slim-Website#213]
Hi,
Slim framework has a great documentation and clean website UI, however we're missing an APIs reference section, maybe to be created under https://slimframework.com/api
I'm sure it will be really appreciated from the community.

I was thinking about https://github.com/FriendsOfPHP/sami

**Comment by svpernova09** [comment]
Looks like the PR was bogged down in the automation of the generation of the docs, is there outstanding work that needs to be done to fix / move this along?

**Comment by akrabat** [comment]
I think some work has been done on this. The key thing for me is that it needs automating in such a way that when we tag a new release, the API docs are regenerated and ideally a PR raised on the slim-website repo with the changes.

**Comment by ghost** [comment]
see https://github.com/slimphp/Slim-Website/pull/230
