### ISSUE TITLE
Tutorial First Application - Composer vendor folder

### ISSUE THREAD

**Issue by odan** [slimphp/Slim-Website#262]
Hi!

I've found some issues on page "Tutorial First Application".

### [Installing Slim Framework](https://www.slimframework.com/docs/tutorial/first-app.html#installing-slim-framework)
The "[Installing Slim Framework](https://www.slimframework.com/docs/tutorial/first-app.html#installing-slim-framework)" section should be updated because the composer `vendor` folder must be installed in the project root folder  `project/vendor/` and not under `project/src/vendor/`.

> (I’m in the src/ directory):

Should be changed to:

> (I’m in the / directory):
or
> (I’m in the project/ directory):

### .gitignore

It's best practice to put the file ".gitignore" into the project root folder:

> .gitignore

### [Create The Application](https://www.slimframework.com/docs/tutorial/first-app.html#icreate-the-application)

The `public` folder should not placed in to `src/public` folder. A better place would be the project root directory.

**Comment by tflight** [comment]
The [index.php](https://github.com/slimphp/Tutorial-First-Application/blob/master/src/public/index.php#L6) file is looking up one directory level for the vendor folder, where it should be found. See the [Getting Set Up](https://www.slimframework.com/docs/tutorial/first-app.html#getting-set-up) section above it. From `src/public/index.php` it will look inside `src/` for the vendor folder, which it should find.

Most people do seem to put their vendor folder in the root of their project, but so long as your `index.php` has the correct location to the vendor folder (and thus the autoloader) I think everything should be fine. Or is there a reference somewhere else causing it to not work? The project seems to work fine for me.

**Comment by odan** [comment]
I think this tutorial should follow good practices and the directory structure of [Slim-Skeleton](https://github.com/slimphp/Slim-Skeleton). This would make life easier for beginners and less confusing (very important especially for beginners).

Example:

`config/` configuration files 
`public/`  web server files (with index.php and .htaccess)
`templates/`  template files
`resources/`  other resource files
`src/`  PHP source code (The App namespace)
`tests/`   test code
`temp/` - temporary files (logfiles, cache)

Project root files:
`composer.json` 
`.gitignore`
`README.md`

**Comment by svpernova09** [comment]
Once we get #282 sorted out I'd like to take a stab at refactoring the tutorial page
