### ISSUE TITLE
simple CORS example returns 405 instead of 404

### ISSUE THREAD

**Issue by llvdl** [slimphp/Slim-Website#273]
The simple CORS example on the [Enabling CORS page](https://www.slimframework.com/docs/cookbook/enable-cors.html) returns a 405 error instead of a 404 error if a resource is not found.

The error message is 

    Method not allowed: 
    Method not allowed. Must be one of: <strong>OPTIONS</strong>

The cause is the OPTIONS route, that matches all patterns, but only the OPTIONS method:

```php
$app->options('/{routes:.+}', function ($request, $response, $args) {
    return $response;
});
```

This can be fixed by appending a catch all route to serve a 404 Not found page as such:

```php
// Catch-all route to serve a 404 page if none of the routes match,
// otherwise Slim will return a 405 error stating that only OPTIONS is allowed.
// NOTE: make sure this route is defined last
$app->map(['GET', 'POST', 'PUT', 'DELETE', 'PATCH'], '/{routes:.+}', function($req, $res) {
        $handler = $this->notFoundHandler; // handle using the default Slim page not found handler
        return $handler($req, $res);
});
```

**Comment by llvdl** [comment]
http://discourse.slimframework.com/t/405-method-not-allowed-using-angular-4s-httpclient/2128/3

**Comment by drum445** [comment]
Hi @llvdl, this snippet causes requests that should return a 405 to return a 404. Is there a way to fix this please?

Example: 
A POST request to /customer that has the routes:
$app->get('/customer', 'CustomerController:getAll');

Will return a 404, when should be 405
