### ISSUE TITLE
Proposing Documentation URL / structure changes

### ISSUE THREAD

**Issue by svpernova09** [slimphp/Slim-Website#281]
Hi all o/

I talked with @akrabat at Sunshine PHP about how I could potentially help out and he mentioned some potential changes to the documentation.

My proposal is to move the current documentation files to `docs/v3` (and obviously update links). The goal with this move is to prepare for `docs/v4`.

This will break a TON of things for people with existing bookmarks and I have a solution for this: A custom 404 page that has a bit of JavaScript to check if the current URL contains `/docs/` and if it matches we'll redirect to `/docs/v3`. This can be updated to whatever the current version of the docs may be. I have this in a local version of the repo and it works well.

Another part of this (maybe not in the same PR) but I'd like to see a dropdown menu to easily swap between versions.

Before I do more down this path Rob asked me to open an issue and get some feedback. Any concerns or thoughts?

**Comment by silentworks** [comment]
I am happy for this change to happen.

**Comment by akrabat** [comment]
First PR is here: #282

**Comment by svpernova09** [comment]
Closing this as we've merged #282 which was the primary goal here.
