### ISSUE TITLE
No input element in the page matches #docsearch

### ISSUE THREAD

**Issue by odan** [slimphp/Slim-Website#290]
Hi!

The following error message appears on the Slim start page: https://www.slimframework.com/

Chrome 63 and 64:

```
Uncaught Error: Error: No input element in the page matches #docsearch
    at Function.value (docsearch.min.js:sourcemap:2)
    at new t (docsearch.min.js:sourcemap:2)
    at e (docsearch.min.js:sourcemap:2)
    at (index):306
```

Firefox 58.0.2 (64-Bit):

```
Error: Error: No input element in the page matches #docsearch

Source-Map-Error: request failed with status 404
Ressource-Address: https://cdn.jsdelivr.net/docsearch.js/1/docsearch.min.js
Source-Map-Address: dist/cdn/docsearch.min.js.map
```

**Comment by svpernova09** [comment]
I'm not seeing it on Chrome Version 64.0.3282.167 (Official Build) (64-bit) or Firefox 58.0.2 (64-bit)

Anyone else able to reproduce?

**Comment by silentworks** [comment]
Yeah I am getting the same error. This has to do with an external resource.

**Comment by svpernova09** [comment]
Ah! I'm seeing it now, that's really odd. Will look into it.
