### ISSUE TITLE
Not always easy to spot which version of the docs you're reading

### ISSUE THREAD

**Issue by tflight** [slimphp/Slim-Website#292]
One downside to the otherwise fantastic https://github.com/slimphp/Slim-Website/pull/282 is that it isn't always clear which version of the docs you might have landed on from a search. For example, if I type "document root" into the search form and click the second result, I end up here https://www.slimframework.com/docs/v2/request/paths.html#resource-uri

Since I'm scrolled down to the `#resource-uri` anchor, there is nothing I see that would give away that I'm on v2 of the docs, not v3. Sure, I can scroll up and check for the little version dropdown, but since the v2 docs were not previously part of the search results, I never think of it.

I'm not sure the correct approach to address this. Excluding v2 docs from the search results doesn't seem right (if even possible). Having the results take you directly to the anchor is nice too, so I wouldn't want to give that up.

Maybe change the background color of the docs based on version? Maybe a big colored version dropdown fixed to the top of the page (ala version selector in the Laravel docs)?

Now that I've been tripped by it I'm aware, but I wonder how many other people have been bitten by it as well.

**Comment by svpernova09** [comment]
I think this brings up 2 good things

* the dropdown needs to be styled to look nice/fancy/stand out
* the docs should have a large banner at the top of each page with "WELCOME TO V2/v3 DOCS" or something that isn't ridiculous but easily sets apart the versions.

**Comment by silentworks** [comment]
I will see if I can look into these two over the weekend. It would be useful if the search only searched the current docs the user is viewing also, but will need to investigate if that is possible.

**Comment by chris48s** [comment]
> the docs should have a large banner at the top of each page with "WELCOME TO V2/v3 DOCS" or something that isn't ridiculous but easily sets apart the versions.

:+1: Something a lot like this on each page of the docs (not just the front page) would be ideal I think:

![screenshot at 2018-03-02 22 29 29](https://user-images.githubusercontent.com/6025893/36925231-c64131dc-1e69-11e8-944f-2d58505bc04f.png)

> the dropdown needs to be styled to look nice/fancy/stand out

:+1: I've always thought the floating version picker on the django docs is quite a good example of this being done well.. it is not in the way, but it is obvious and always there when you need it:

![gifrecord_2018-03-02_223242](https://user-images.githubusercontent.com/6025893/36925299-259ff0f0-1e6a-11e8-8495-8a4c3621f933.gif)

**Comment by l0gicgate** [comment]
Added fix in #306. The version of docs browsed will be displayed in header. This issue can be closed @akrabat
