### ISSUE TITLE
Wrong Documentation - Deployment

### ISSUE THREAD

**Issue by filips123** [slimphp/Slim-Website#299]
In the Deployment section of Documentation (https://www.slimframework.com/docs/v3/deployment/deployment.html), there is a chapter for deploying to a shared server.
There is a code for `.htaccess`:
```
<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteRule ^$ public/     [L]
   RewriteRule (.*) public/$1 [L]
</IfModule>
```
This code will cause `Internal Server Error` because `Request exceeded the limit of 10 internal redirects due to probable configuration error`.
The code should be:
```
<IfModule mod_rewrite.c>
   RewriteEngine on
   RewriteRule ^$ public/ [L]
   RewriteRule (^[^/]*$) public/$1 [L]
</IfModule>
```
See https://stackoverflow.com/a/1611562/6523409

**Comment by l0gicgate** [comment]
Fixed in #306 this can be closed @akrabat
