### ISSUE TITLE
Update tutorial for Slim 4

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Website#309]

**Comment by odan** [comment]
I'm trying to add a Slim 4 tutorial [here](https://gist.github.com/odan/e416553873f6ae60e28ba96d6e0873e6), but it's not finished yet.

In the meantime, we could offer a list of existing Slim 4 tutorials like:

* https://odan.github.io/2019/11/05/slim4-tutorial.html

What do you think?

**Comment by l0gicgate** [comment]
@odan looks great, I do think this would benefit from using Zend DB though which makes it easier for query building.

**Comment by odan** [comment]
What would be better?

Option 1: I copy and "update" the existing Slim 3 tutorial  to a Slim 4 tutorial. [Example](https://gist.github.com/odan/e416553873f6ae60e28ba96d6e0873e6) (Draft)
Option 2: I copy my existing [Slim 4 tutorial](https://odan.github.io/2019/11/05/slim4-tutorial.html) and extend it with a query builder?
Option 3: I create a curated list with links to Slim 4 tutorials

**Comment by l0gicgate** [comment]
@odan that's entirely up to you, I think option 2 and 3 are both viable. I think the Slim 3 tutorial is fairly dated at this point.

**Comment by akrabat** [comment]
I vote for 2 _and_ 3

**Comment by tomshaw** [comment]
A tutorial how to use the latest skeleton/mvc to create a crud app would be helpful.
