### ISSUE TITLE
Search for “middleware” leads to v2 docs from v3 docs

### ISSUE THREAD

**Issue by Rarst** [slimphp/Slim-Website#321]
If you search v3 docs for "middleware" **the first result** confusingly sends you to v2 docs https://www.slimframework.com/docs/v2/routing/middleware.html instead of v3 docs https://www.slimframework.com/docs/v3/concepts/middleware.html

![slim-docs-middleware](https://user-images.githubusercontent.com/737584/48153367-b4d81300-e2ce-11e8-86d5-d99a947a11cb.png)

**Comment by tflight** [comment]
Related: https://github.com/slimphp/Slim-Website/issues/292

**Comment by l0gicgate** [comment]
I just looked into this. Once the new docs are up, I'll request for a new crawl from Algolia.

**Comment by slokhorst** [comment]
Same issue when browsing the Slim 4 docs: it shows results from older versions.
