### ISSUE TITLE
Sites/Application Using Slim

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim-Website#331]
This is in relation to [Slim issue #2524](https://github.com/slimphp/Slim/issues/2524).

Adding a page like [Facebook's Sites-Using-React Page](https://github.com/facebook/react/wiki/Sites-Using-React) may help attract newcomers.

This could be a community generated page with stories shared by users.

**Comment by odan** [comment]
In the meantime the React Wiki page is gone. 
The Slim Wiki page has been updated: https://github.com/slimphp/Slim/wiki
Closing this as completed.
