### ISSUE TITLE
[4.x] Non-PSR-7 method withJson() mentioned

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Website#384]
Hi everyone

There is a Reminder-Block which mentions the `withJson()` method on the `Response` object. As this is not a PSR-7 standard method, either we should remove this reminder or add another reminder (heads up), that there is the slim http decorator which would provide additional methods, inclusive `withJson()`.

https://github.com/slimphp/Slim-Website/blob/8e3121cf8a7f9860c933599c993354b77afc755a/docs/v4/objects/response.md#L286-L293

**Comment by l0gicgate** [comment]
We should probably remove it

**Comment by adriansuter** [comment]
I think, we should add a section about the slim http decorator third-party to the docs and put a link to that.

First this is promotion for the Slim-Http library and second Slim-Http really does provide useful additional methods that would be probably used by most developers.

Using Slim-Http does feel to make Slim more complete. Otherwise you are tempted to write your own sort of decorator and put a method into the action/controller. This works, but the logic should be added to the response object, not the action/controller, in my opinion.

**Comment by l0gicgate** [comment]
Yeah, that's not a bad idea. I'll be honest I'm dreading creating docs for Slim-Http 😂 but we absolutely should.

**Comment by adriansuter** [comment]
I do understand. And I am hesitating because English is not my native language 🤔.
