### ISSUE TITLE
[4.x] Change examples to use middleware helpers

### ISSUE THREAD

**Issue by adriansuter** [slimphp/Slim-Website#398]
We should change the example codes of Slim 4 to use the new middleware helpers `App::addRoutingMiddleware` and `App::addErrorMiddleware` by default.

For example: Get started > Home > How does it work? > Figure 1: Example Slim application

And somewhere we should write how it's been done without the helper methods.

**Comment by l0gicgate** [comment]
Yes, we need to change all the examples so people understand to adopt that pattern.
