### ISSUE TITLE
Extended Cookbook

### ISSUE THREAD

**Issue by JustSteveKing** [slimphp/Slim-Website#412]
In versions 2 & 3 the User Guide had quite a few extra pages within the cook book. I think with the dramatic change of approach in Slim 4 these need to resurface if not be added to. 

Examples of using non slim components for PSR-7 or using `league/container` to show the pluggable behaviour of Slim 4 in more detail. I think most people could get Eloquent etc up and running well enough.

**Comment by l0gicgate** [comment]
That's on the todo list. Once the dust settles and we get most of the kinks worked out on Slim 4 we're going to focus on better docs.

**Comment by JustSteveKing** [comment]
Excellent! I shall become available on slack if you want help or suggestions
