### ISSUE TITLE
CORS middleware simple solution does not work for preflight - needs additional method

### ISSUE THREAD

**Issue by edeych** [slimphp/Slim-Website#433]
The example [here](http://www.slimframework.com/docs/v4/cookbook/enable-cors.html) for simple solution produces the following CORS error in Chrome:

**Response to preflight request doesn't pass access control check: It does not have HTTP ok status.**

I resolved this by adding the following after the last ->withHeader:

`->withStatus(200);`

If this can be replicated by anyone else, please consider updating the documentation. It is worth noting that I have the following header set

`header('Access-Control-Allow-Credentials:true');`

**Comment by l0gicgate** [comment]
That's only if you carry cookies, authorization headers or TLS client certificates with your request, which may not apply to all.
