### ISSUE TITLE
Optional parameters in routes

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Website#44]
The Route placeholders section needs to also document how to do optional parameters.

**Comment by silentworks** [comment]
Optionals, who need optionals. Required all the things.

**Comment by geekish** [comment]
:thumbsup: Can I suggest splitting the routing doc into multiple pages if you add any more?

**Comment by tflight** [comment]
@geggleto isn't this [here](https://www.slimframework.com/docs/objects/router.html#optional-segments) ([commit](https://github.com/slimphp/Slim-Website/commit/1d063fe3dceee76b4b23d24ca1ab2f9bcfb86d73)) or are you looking for something else?
