### ISSUE TITLE
Redundant Slim 4 documentation

### ISSUE THREAD

**Issue by odan** [slimphp/Slim-Website#442]
If I google for [slim 4 documentation](https://www.google.com/search?q=slim+4+documentation&oq=slim+4+documentation), the old documentation site is listed as first entry.

![image](https://user-images.githubusercontent.com/781074/67515231-8cdbee00-f69e-11e9-8559-818cd579d72d.png)

My concern is, that people could read outdated information about Slim 4.

**Comment by l0gicgate** [comment]
I took down the other site. It's gone from search results now
