### ISSUE TITLE
Please bring back withJson in v4

### ISSUE THREAD

**Issue by kgrosvenor** [slimphp/Slim-Website#448]
Hey guys, i'm happy V4 of slim is out, but one thing i am not quite so sure on is the new method for returning JSON, it is much more code then in previous versions of slim, may i ask why it's been removed, and if there is any plan to add it back - it was such a great method.

**Comment by l0gicgate** [comment]
Slim V4 is PSR-7 agnostic. You can use the decorator repo we provide with your PSR-7 implementation if you want this functionality back.

https://github.com/slimphp/Slim-Http

**Comment by kgrosvenor** [comment]
Will have a look, thank you 💯
