### ISSUE TITLE
Update Required Services documentation

### ISSUE THREAD

**Issue by silentworks** [slimphp/Slim-Website#45]
We need to document the actual services that need to be in the Container in order for Slim to work. Also stating which objects should be shared and which should be new on each call.

**Comment by ppetermann** [comment]
something like http://www.slimframework.com/docs/concepts/di.html "Required Services"?

**Comment by silentworks** [comment]
Haha, thanks for that. I guess I just need to improve that as it doesn't tell you that Request and Response need to be new instances and it doesn't have code examples of what it looks like in the default container which might be useful.

**Comment by silentworks** [comment]
@ppetermann Might be better to change the title of that to Service Container also, what are your thoughts?

**Comment by ppetermann** [comment]
well containers like that are commonly called dependency containers, di-containers etc. so i think the naming is ok

**Comment by JoeBengalen** [comment]
@silentworks Request and Response do NOT return new instances on each call. See https://github.com/slimphp/Slim/blob/3.x/Slim/Container.php#L121. Just services, no factory method.

This was changed due to something in the container interop if I remember correctly. Is stated that the same instance should be returned

Edit:
This was the text I mean:
"Two successive calls to `get` with the same identifier SHOULD return the same value."

https://github.com/container-interop/container-interop/blob/master/docs/ContainerInterface.md#11-basics

**Comment by ppetermann** [comment]
@JoeBengalen yah thats container-interop not taking into account the need for factories.
by that logic the service that needs to be registered should be a factory, and $container->get('request') should return the factory, which slim then would need to use - which is not happening at the moment either.
Always returning the same instance of request/response is problematic, as you specifically might want to get a new (clean) instance.

**Comment by JoeBengalen** [comment]
Don't think it will be a problem in this case since the request and response objects are immutable.

**Comment by silentworks** [comment]
@JoeBengalen you mean in the PSR right?

**Comment by JoeBengalen** [comment]
For now Slim includes https://github.com/container-interop/container-interop, not the psr (which is not final anyway?)

**Comment by silentworks** [comment]
@JoeBengalen it must be related to PSR-7, because container interop also states "However, depending on the implementor design and/or user configuration, different values might be returned, so user SHOULD NOT rely on getting the same value on 2 successive calls."

**Comment by JoeBengalen** [comment]
It does say that, but if I remember correctly this was the reason for removing all factories from the container.

**Comment by JoeBengalen** [comment]
Check this out:

https://github.com/slimphp/Slim/pull/1362

**Comment by ppetermann** [comment]
rfc2119 should vs must.

**Comment by geggleto** [comment]
Not sure if this is relevant as we are working on v4

**Comment by geggleto** [comment]
Actually the DI page does this already :)
