### ISSUE TITLE
DOCS: Installation: Where to put the "Hello World" script?

### ISSUE THREAD

**Issue by Taitava** [slimphp/Slim-Website#452]
A quotation from this doc file: `docs/v4/start/installation.md`
>    ## Step 4: Hello World
>    ```php
>    <?php
>    use Psr\Http\Message\ResponseInterface as Response;
>    use Psr\Http\Message\ServerRequestInterface as Request;
>    use Slim\Factory\AppFactory;
>    
>    require __DIR__ . '/../vendor/autoload.php';
>    
>    $app = AppFactory::create();
>    
>    $app->get('/', function (Request $request, Response $response, $args) {
>        $response->getBody()->write("Hello world!");
>        return $response;
>    });
>    
>    $app->run();
>    ```

I think the documentation should mention the file path where this example code should be saved. Thanks! :)

**Comment by odan** [comment]
We could add something like: 

File: `public/index.php`
