### ISSUE TITLE
Differentiating PSR 7 vs SlimPHP 3 approches in code snippets in the documentation

### ISSUE THREAD

**Issue by rotexdegba** [slimphp/Slim-Website#46]
Hi There,

I want to suggest that pure PSR 7 alternative snippets be made available in the documentation; like in the snippet below:

``` php
<?php
// Create and configure Slim app
$app = new \Slim\App;

// Define app routes
$app->get('/hello/{name}', function ($request, $response, $args) {

    //Using the Slim3 Non PSR-7 write helper method on the Response Object
    return $response->write("Hello " . $args['name']);

    //OR 
    // Strictly sticking to the PSR-7 API for Response Objects
    $response->getBody()->write("Hello " . $args['name']);
    return $response;
});

// Run app
$app->run();
```

I believe this will allow developers learning Slim 3 to decide if they want to strictly stick to using the PSR-7 APIs for the Request and Response objects, to make swapping out different PSR-7 Implementations of the Request and Response objects, easier.

Thanks

**Comment by akrabat** [comment]
Fine with me. Feel free to submit a PR.

**Comment by geggleto** [comment]
Going to close this as no PR has been written and it's 2 years old now :)
