### ISSUE TITLE
Document PSR-3 Logging

### ISSUE THREAD

**Issue by l0gicgate** [slimphp/Slim-Website#488]
See https://github.com/slimphp/Slim/pull/2937

**Comment by elazar** [comment]
@l0gicgate Happy to help out with this. Could use guidance as to the best place for the content to go within the docs. (Concepts? Cookbook?)

**Comment by l0gicgate** [comment]
I would say we need to modify http://www.slimframework.com/docs/v4/middleware/error-handling.html
