### ISSUE TITLE
Apache .htaccess script not working

### ISSUE THREAD

**Issue by TomMarti** [slimphp/Slim-Website#490]
When i try to use the default .htaccess script, the routes with params not work.

**Comment by odan** [comment]
Hi @TomMarti Can you please add more details?

**Comment by TomMarti** [comment]
@odan Ok, 

When I use the .htaccess script offer in the slimframework documentation, i got a server 404 error.

But when i use the script from the version 3 of slim it's work but i can't get my existing folder.

I'm sorry for the very bad english.

**Comment by odan** [comment]
There should be some answers about this common issue in the web.

Try to set the correct basePath:

* http://www.slimframework.com/docs/v4/start/web-servers.html#run-from-a-sub-directory

This here works for me: https://github.com/selective-php/basepath#installation

**Comment by TomMarti** [comment]
Ok thanks it's work for me to. 👍
