### ISSUE TITLE
[Migration] Middleware signature changed

### ISSUE THREAD

**Issue by igorsantos07** [slimphp/Slim-Website#496]
Also something I'm not able to write about, but definitely another breaking change in my current application (basically middlewares changed a lot since v2! - glad my application only uses one).

> moved from slimphp/Slim#2941

**Comment by odan** [comment]
The middleware for Slim 3 and 4 is already documented [here](https://www.slimframework.com/docs/v4/concepts/middleware.html) and [here](https://www.slimframework.com/docs/v3/concepts/middleware.html). Slim 2 is not supported anymore and Slim 3 is in maintenance mode (as far as I know). What do you think is missing?
