### ISSUE TITLE
Search isn't working - no results are returned and error in the console

### ISSUE THREAD

**Issue by AnnaDodson** [slimphp/Slim-Website#498]
Hitting enter in the search input field doesn't return any results or validation to the user, I checked the console and the following error is being returned:

```
Uncaught (in promise) AlgoliaSearchError {name: "AlgoliaSearchError",
message: "Operations quota exceeded, change plan to get more Operations.",
statusCode: 403
```

**Comment by l0gicgate** [comment]
Unfortunately we are on a free plan for the search, there isn't much we can do about that.
