### ISSUE TITLE
Styling Problems in Lifecycle page

### ISSUE THREAD

**Issue by iursevla** [slimphp/Slim-Website#521]
This is how I see it, now:

![image](https://user-images.githubusercontent.com/13489488/91983151-3100dd80-ed23-11ea-9d3b-24831a76d00d.png)

When the screen width is smaller than 596px it's correctly shown.

**Comment by odan** [comment]
I cannot reproduce it in any browser.

@iursevla Does this issue still exists for this page?

* https://www.slimframework.com/docs/v4/concepts/life-cycle.html

**Comment by iursevla** [comment]
@odan yes.

Saw the same on:  `Chrome Version 86.0.4240.198 (Official Build) (x86_64)`

Example:

![image](https://user-images.githubusercontent.com/13489488/99358258-2deaa780-28a5-11eb-89bb-34dc79ffdca9.png)
