### ISSUE TITLE
SSL issue

### ISSUE THREAD

**Issue by odan** [slimphp/Slim-Website#542]
Hi! Currently, the Slim website is only SSL-protected for the www subdomain.

* https://www.slimframework.com/ -> works
* https://slimframework.com/  -> error

> Your connection is not private
Attackers might be trying to steal your information from slimframework.com (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

![image](https://user-images.githubusercontent.com/781074/104852824-54f14400-58fd-11eb-8d16-499513999e6d.png)

SSL Info

* https://www.sslshopper.com/ssl-checker.html#hostname=www.slimframework.com -> OK
* https://www.sslshopper.com/ssl-checker.html#hostname=slimframework.com -> Errors

**Comment by l0gicgate** [comment]
@akrabat can we add a redirect at the DNS level to fix this?

**Comment by akrabat** [comment]
I've pressed buttons with the registrar and this should now be solved and work as you'd expect.
