### ISSUE TITLE
misinfo in docs regarding method getQueryParams

### ISSUE THREAD

**Issue by finklez** [slimphp/Slim-Website#59]
i'm new to 3.x so please excuse me if i'm mistaken or misinterpret the docs, it seems getQueryParams is a method of the parent Request class and not the Uri

the relevant section follows:

> The PSR 7 Request object's URI is itself an object that provides the following methods to inspect the HTTP request's URL parts:
> 
> getScheme()
> getHost()
> getPort()
> getPath()
> getBasePath()
> getQuery() (returns string)
> getQueryParams() (returns associative array)

**Comment by llvdl** [comment]
This issue has been fixed by https://github.com/slimphp/Slim-Website/commit/deffa075e69a054200e0acd496ae34fae926aae7 and can be closed.
