### ISSUE TITLE
Passing variables from middleware 

### ISSUE THREAD

**Issue by akrabat** [slimphp/Slim-Website#62]
From: http://help.slimframework.com/discussions/questions/8833-slim-3-pass-variables-from-middleware:

> Rob, 
> That is very easy. Thank you. I couldn't find that method anywhere in the docs. This info might be very helpful to add to the new docs for new people like myself. Perhaps in the Request Helpers section (http://www.slimframework.com/docs/objects/request.html#request-helpers) or the Middleware section > (http://www.slimframework.com/docs/concepts/middleware.html).
> 
> Again, thank you, 
> Sam
> 
> > On Fri, Nov 06 at 07:09 AM, Rob Allen wrote:
> > 
> > The easiest way is to use the request's attributes:
> > 
> > In middleware:
> > 
> > ```
> > $request = $request->withAttribute('foo', 'bar');
> > ```
> > 
> > In route callback:
> > 
> > ```
> > $foo = $request->getAttribute('foo');
> > ```

**Comment by geggleto** [comment]
Related to #189

**Comment by geggleto** [comment]
closing this one :)
