### ISSUE TITLE
Talk more about skeleton, talk a bit at all about console!

### ISSUE THREAD

**Issue by carlosmintfan** [slimphp/Slim-Website#706]
What about https://github.com/slimphp/Slim-Console? I don't see any info about it on the website. Also, the skeleton is mentioned on the homepage, but not in the docs. It should be mentioned there too.

EDIT: If the console is very new WIP and not really usable, don't mention it, I haven't looked at it very much. But the skeleton at least.

**Comment by odan** [comment]
The console is WIP. If you have further questions about the current status, please create an issue here: 
https://github.com/slimphp/Slim-Console/issues
