### ISSUE TITLE
Explain the ability to use PSR-15 middleware

### ISSUE THREAD

**Issue by carlosmintfan** [slimphp/Slim-Website#711]
https://www.slimframework.com/docs/v4/concepts/middleware.html talks about closures and invokable classes as middlewares. However, instead of writing a class with an `__invoke()` method, you could also write a class with a `process()` instead of an `__invoke()` method if it implements `\PSR\Http\Server\MiddlewareInterface`. That should be explained.

**Comment by odan** [comment]
The page about routing already explains that you can implement a class with a `__invoke()` method as a rote handler. But this invokable class is not a middleware. How middlewares can be implemented can be found on this [page](https://www.slimframework.com/docs/v4/concepts/middleware.html).

**Comment by carlosmintfan** [comment]
The middleware page doesn't talk about psr-15 middlewares with a process method. Oh, the routing link was an error, I think. I'm talking about middleware :)

**Comment by odan** [comment]
Yes, this part about PSR-15 middlewares with a process method is missing. 

@akrabat Maybe we should reconsider this PR again: https://github.com/slimphp/Slim-Website/pull/662

**Comment by akrabat** [comment]
> Yes, this part about PSR-15 middlewares with a process method is missing.
> 
> @akrabat Maybe we should reconsider this PR again: #662

Yes, I agree.
