### ISSUE TITLE
Update Closure binding - Slim3 doc

### ISSUE THREAD

**Issue by mathmarques** [slimphp/Slim-Website#75]
$this is now \Slim\Container 

Q: Should we say that $this is a \Slim\Container or a Interop\Container\ContainerInterface?

**Comment by codeguy** [comment]
Probably say that it is a `ContainerInterface` with the caveat that `__get()` and `__set()` magic methods are only available with Slim's container.

**Comment by akrabat** [comment]
I agree with @codeguy
