### ISSUE TITLE
migration doc enhancements

### ISSUE THREAD

**Issue by mbretter** [slimphp/Slim-Website#83]
route middleware with args:
Slim2:

```
$app->get('/foo/bar', $authorize('whatever'), function () use ($app)
```

in Slim3

```
$app->get('/foo/bar', function ($request, $response, $args) use ($app)
...
})->add($authorize('whatever'));
```

Slim2 container, if having tons of $app-> access in your application:

```
$app->cache->get(...
```

in Slim3

```
$slim = new \Slim\App(....)
$app = $slim->getContainer();
$app->cache->get(...
```

**Comment by mbretter** [comment]
another one, getting current route
Slim2

```
$app->router()->getCurrentRoute()
```

Slim3

```
$request->getAttribute('route')
```

if used in app middleware
 'determineRouteBeforeAppMiddleware' => true,
must be set, otherweise $request->getAttribute('route') returns null

**Comment by geggleto** [comment]
Going to close this as well.
