### ISSUE TITLE
How do i run this locally

### ISSUE THREAD

**Issue by victorlenerd** [slimphp/Slim-Website#89]
Am trying to run this page locally. I've used jekyll server

but it keep returning this error below...

Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:92:in `block in materialize': Could not find RedCloth-4.2.9 in any of the sources (Bundler::GemNotFound)
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in`map!'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/spec_set.rb:85:in `materialize'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/definition.rb:140:in`specs'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/definition.rb:185:in `specs_for'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/definition.rb:174:in`requested_specs'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/environment.rb:18:in `requested_specs'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler/runtime.rb:13:in`setup'
    from /Library/Ruby/Gems/2.0.0/gems/bundler-1.10.6/lib/bundler.rb:127:in `setup'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:38:in`require_from_bundler'
    from /Library/Ruby/Gems/2.0.0/gems/jekyll-3.0.1/bin/jekyll:13:in `<top (required)>'
    from /usr/local/bin/jekyll:23:in`load'
    from /usr/local/bin/jekyll:23:in `<main>'

pleas help me.

**Comment by lornajane** [comment]
I've just had the same problem.  Try this:

`bundle install`

Then, to get it running locally, try this:

`bundle exec jekyll serve`

If this works, then one of us should add this information to the readme file :)

**Comment by akrabat** [comment]
I've updated the README with the relevant information in hopefully enough detail to get people started.
